// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAIN_H_
#define FLATBUFFERS_GENERATED_MAIN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "ntwindow_generated.h"

struct Envelope;
struct EnvelopeBuilder;

enum Domain : int8_t {
  Domain_None = 0,
  Domain_Ntwindow = 1,
  Domain_MIN = Domain_None,
  Domain_MAX = Domain_Ntwindow
};

inline const Domain (&EnumValuesDomain())[2] {
  static const Domain values[] = {
    Domain_None,
    Domain_Ntwindow
  };
  return values;
}

inline const char * const *EnumNamesDomain() {
  static const char * const names[3] = {
    "None",
    "Ntwindow",
    nullptr
  };
  return names;
}

inline const char *EnumNameDomain(Domain e) {
  if (::flatbuffers::IsOutRange(e, Domain_None, Domain_Ntwindow)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDomain()[index];
}

struct Envelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DOMAIN = 4,
    VT_NTWINDOW_TYPE = 6,
    VT_NTWINDOW = 8
  };
  Domain domain() const {
    return static_cast<Domain>(GetField<int8_t>(VT_DOMAIN, 0));
  }
  NtwindowPayload ntwindow_type() const {
    return static_cast<NtwindowPayload>(GetField<uint8_t>(VT_NTWINDOW_TYPE, 0));
  }
  const void *ntwindow() const {
    return GetPointer<const void *>(VT_NTWINDOW);
  }
  template<typename T> const T *ntwindow_as() const;
  const AttachWindow *ntwindow_as_AttachWindow() const {
    return ntwindow_type() == NtwindowPayload_AttachWindow ? static_cast<const AttachWindow *>(ntwindow()) : nullptr;
  }
  const SetWindowRect *ntwindow_as_SetWindowRect() const {
    return ntwindow_type() == NtwindowPayload_SetWindowRect ? static_cast<const SetWindowRect *>(ntwindow()) : nullptr;
  }
  const DetachWindow *ntwindow_as_DetachWindow() const {
    return ntwindow_type() == NtwindowPayload_DetachWindow ? static_cast<const DetachWindow *>(ntwindow()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_DOMAIN, 1) &&
           VerifyField<uint8_t>(verifier, VT_NTWINDOW_TYPE, 1) &&
           VerifyOffset(verifier, VT_NTWINDOW) &&
           VerifyNtwindowPayload(verifier, ntwindow(), ntwindow_type()) &&
           verifier.EndTable();
  }
};

template<> inline const AttachWindow *Envelope::ntwindow_as<AttachWindow>() const {
  return ntwindow_as_AttachWindow();
}

template<> inline const SetWindowRect *Envelope::ntwindow_as<SetWindowRect>() const {
  return ntwindow_as_SetWindowRect();
}

template<> inline const DetachWindow *Envelope::ntwindow_as<DetachWindow>() const {
  return ntwindow_as_DetachWindow();
}

struct EnvelopeBuilder {
  typedef Envelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_domain(Domain domain) {
    fbb_.AddElement<int8_t>(Envelope::VT_DOMAIN, static_cast<int8_t>(domain), 0);
  }
  void add_ntwindow_type(NtwindowPayload ntwindow_type) {
    fbb_.AddElement<uint8_t>(Envelope::VT_NTWINDOW_TYPE, static_cast<uint8_t>(ntwindow_type), 0);
  }
  void add_ntwindow(::flatbuffers::Offset<void> ntwindow) {
    fbb_.AddOffset(Envelope::VT_NTWINDOW, ntwindow);
  }
  explicit EnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Envelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Envelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Envelope> CreateEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Domain domain = Domain_None,
    NtwindowPayload ntwindow_type = NtwindowPayload_NONE,
    ::flatbuffers::Offset<void> ntwindow = 0) {
  EnvelopeBuilder builder_(_fbb);
  builder_.add_ntwindow(ntwindow);
  builder_.add_ntwindow_type(ntwindow_type);
  builder_.add_domain(domain);
  return builder_.Finish();
}

inline const Envelope *GetEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<Envelope>(buf);
}

inline const Envelope *GetSizePrefixedEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Envelope>(buf);
}

inline bool VerifyEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Envelope>(nullptr);
}

inline bool VerifySizePrefixedEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Envelope>(nullptr);
}

inline void FinishEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Envelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Envelope> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_MAIN_H_
