// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MEWINDOW_H_
#define FLATBUFFERS_GENERATED_MEWINDOW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct AttachWindow;
struct AttachWindowBuilder;

struct SetWindowRect;
struct SetWindowRectBuilder;

struct DetachWindow;
struct DetachWindowBuilder;

enum MewindowPayload : uint8_t {
  MewindowPayload_NONE = 0,
  MewindowPayload_AttachWindow = 1,
  MewindowPayload_SetWindowRect = 2,
  MewindowPayload_DetachWindow = 3,
  MewindowPayload_MIN = MewindowPayload_NONE,
  MewindowPayload_MAX = MewindowPayload_DetachWindow
};

inline const MewindowPayload (&EnumValuesMewindowPayload())[4] {
  static const MewindowPayload values[] = {
    MewindowPayload_NONE,
    MewindowPayload_AttachWindow,
    MewindowPayload_SetWindowRect,
    MewindowPayload_DetachWindow
  };
  return values;
}

inline const char * const *EnumNamesMewindowPayload() {
  static const char * const names[5] = {
    "NONE",
    "AttachWindow",
    "SetWindowRect",
    "DetachWindow",
    nullptr
  };
  return names;
}

inline const char *EnumNameMewindowPayload(MewindowPayload e) {
  if (::flatbuffers::IsOutRange(e, MewindowPayload_NONE, MewindowPayload_DetachWindow)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMewindowPayload()[index];
}

template<typename T> struct MewindowPayloadTraits {
  static const MewindowPayload enum_value = MewindowPayload_NONE;
};

template<> struct MewindowPayloadTraits<AttachWindow> {
  static const MewindowPayload enum_value = MewindowPayload_AttachWindow;
};

template<> struct MewindowPayloadTraits<SetWindowRect> {
  static const MewindowPayload enum_value = MewindowPayload_SetWindowRect;
};

template<> struct MewindowPayloadTraits<DetachWindow> {
  static const MewindowPayload enum_value = MewindowPayload_DetachWindow;
};

bool VerifyMewindowPayload(::flatbuffers::Verifier &verifier, const void *obj, MewindowPayload type);
bool VerifyMewindowPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct AttachWindow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AttachWindowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARENT_HWND = 4,
    VT_SHOW = 6
  };
  uint64_t parent_hwnd() const {
    return GetField<uint64_t>(VT_PARENT_HWND, 0);
  }
  bool show() const {
    return GetField<uint8_t>(VT_SHOW, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PARENT_HWND, 8) &&
           VerifyField<uint8_t>(verifier, VT_SHOW, 1) &&
           verifier.EndTable();
  }
};

struct AttachWindowBuilder {
  typedef AttachWindow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parent_hwnd(uint64_t parent_hwnd) {
    fbb_.AddElement<uint64_t>(AttachWindow::VT_PARENT_HWND, parent_hwnd, 0);
  }
  void add_show(bool show) {
    fbb_.AddElement<uint8_t>(AttachWindow::VT_SHOW, static_cast<uint8_t>(show), 0);
  }
  explicit AttachWindowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AttachWindow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AttachWindow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AttachWindow> CreateAttachWindow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t parent_hwnd = 0,
    bool show = false) {
  AttachWindowBuilder builder_(_fbb);
  builder_.add_parent_hwnd(parent_hwnd);
  builder_.add_show(show);
  return builder_.Finish();
}

struct SetWindowRect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetWindowRectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  int32_t width() const {
    return GetField<int32_t>(VT_WIDTH, 0);
  }
  int32_t height() const {
    return GetField<int32_t>(VT_HEIGHT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<int32_t>(verifier, VT_HEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct SetWindowRectBuilder {
  typedef SetWindowRect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(SetWindowRect::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(SetWindowRect::VT_Y, y, 0);
  }
  void add_width(int32_t width) {
    fbb_.AddElement<int32_t>(SetWindowRect::VT_WIDTH, width, 0);
  }
  void add_height(int32_t height) {
    fbb_.AddElement<int32_t>(SetWindowRect::VT_HEIGHT, height, 0);
  }
  explicit SetWindowRectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetWindowRect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetWindowRect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetWindowRect> CreateSetWindowRect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0,
    int32_t width = 0,
    int32_t height = 0) {
  SetWindowRectBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct DetachWindow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DetachWindowBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct DetachWindowBuilder {
  typedef DetachWindow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit DetachWindowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DetachWindow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DetachWindow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DetachWindow> CreateDetachWindow(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  DetachWindowBuilder builder_(_fbb);
  return builder_.Finish();
}

inline bool VerifyMewindowPayload(::flatbuffers::Verifier &verifier, const void *obj, MewindowPayload type) {
  switch (type) {
    case MewindowPayload_NONE: {
      return true;
    }
    case MewindowPayload_AttachWindow: {
      auto ptr = reinterpret_cast<const AttachWindow *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MewindowPayload_SetWindowRect: {
      auto ptr = reinterpret_cast<const SetWindowRect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MewindowPayload_DetachWindow: {
      auto ptr = reinterpret_cast<const DetachWindow *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMewindowPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMewindowPayload(
        verifier,  values->Get(i), types->GetEnum<MewindowPayload>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_MEWINDOW_H_
