// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AttachWindow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AttachWindow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttachWindow(bb:flatbuffers.ByteBuffer, obj?:AttachWindow):AttachWindow {
  return (obj || new AttachWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttachWindow(bb:flatbuffers.ByteBuffer, obj?:AttachWindow):AttachWindow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AttachWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

parentHwnd():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

show():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startAttachWindow(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addParentHwnd(builder:flatbuffers.Builder, parentHwnd:bigint) {
  builder.addFieldInt64(0, parentHwnd, BigInt('0'));
}

static addShow(builder:flatbuffers.Builder, show:boolean) {
  builder.addFieldInt8(1, +show, +false);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(2, id, 0);
}

static endAttachWindow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttachWindow(builder:flatbuffers.Builder, parentHwnd:bigint, show:boolean, id:number):flatbuffers.Offset {
  AttachWindow.startAttachWindow(builder);
  AttachWindow.addParentHwnd(builder, parentHwnd);
  AttachWindow.addShow(builder, show);
  AttachWindow.addId(builder, id);
  return AttachWindow.endAttachWindow(builder);
}
}
