// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DetachWindow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DetachWindow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDetachWindow(bb:flatbuffers.ByteBuffer, obj?:DetachWindow):DetachWindow {
  return (obj || new DetachWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDetachWindow(bb:flatbuffers.ByteBuffer, obj?:DetachWindow):DetachWindow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DetachWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDetachWindow(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDetachWindow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDetachWindow(builder:flatbuffers.Builder):flatbuffers.Offset {
  DetachWindow.startDetachWindow(builder);
  return DetachWindow.endDetachWindow(builder);
}
}
