// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Domain } from './domain.js';
import { NtwindowPayload, unionToNtwindowPayload, unionListToNtwindowPayload } from './ntwindow-payload.js';


export class Envelope {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Envelope {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEnvelope(bb:flatbuffers.ByteBuffer, obj?:Envelope):Envelope {
  return (obj || new Envelope()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEnvelope(bb:flatbuffers.ByteBuffer, obj?:Envelope):Envelope {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Envelope()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

domain():Domain {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Domain.None;
}

ntwindowType():NtwindowPayload {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : NtwindowPayload.NONE;
}

ntwindow<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startEnvelope(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addDomain(builder:flatbuffers.Builder, domain:Domain) {
  builder.addFieldInt8(0, domain, Domain.None);
}

static addNtwindowType(builder:flatbuffers.Builder, ntwindowType:NtwindowPayload) {
  builder.addFieldInt8(1, ntwindowType, NtwindowPayload.NONE);
}

static addNtwindow(builder:flatbuffers.Builder, ntwindowOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, ntwindowOffset, 0);
}

static endEnvelope(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishEnvelopeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedEnvelopeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createEnvelope(builder:flatbuffers.Builder, domain:Domain, ntwindowType:NtwindowPayload, ntwindowOffset:flatbuffers.Offset):flatbuffers.Offset {
  Envelope.startEnvelope(builder);
  Envelope.addDomain(builder, domain);
  Envelope.addNtwindowType(builder, ntwindowType);
  Envelope.addNtwindow(builder, ntwindowOffset);
  return Envelope.endEnvelope(builder);
}
}
