// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AttachWindow } from './attach-window.js';
import { DetachWindow } from './detach-window.js';
import { SetWindowRect } from './set-window-rect.js';


export enum MewindowPayload {
  NONE = 0,
  AttachWindow = 1,
  SetWindowRect = 2,
  DetachWindow = 3
}

export function unionToMewindowPayload(
  type: MewindowPayload,
  accessor: (obj:AttachWindow|DetachWindow|SetWindowRect) => AttachWindow|DetachWindow|SetWindowRect|null
): AttachWindow|DetachWindow|SetWindowRect|null {
  switch(MewindowPayload[type]) {
    case 'NONE': return null; 
    case 'AttachWindow': return accessor(new AttachWindow())! as AttachWindow;
    case 'SetWindowRect': return accessor(new SetWindowRect())! as SetWindowRect;
    case 'DetachWindow': return accessor(new DetachWindow())! as DetachWindow;
    default: return null;
  }
}

export function unionListToMewindowPayload(
  type: MewindowPayload, 
  accessor: (index: number, obj:AttachWindow|DetachWindow|SetWindowRect) => AttachWindow|DetachWindow|SetWindowRect|null, 
  index: number
): AttachWindow|DetachWindow|SetWindowRect|null {
  switch(MewindowPayload[type]) {
    case 'NONE': return null; 
    case 'AttachWindow': return accessor(index, new AttachWindow())! as AttachWindow;
    case 'SetWindowRect': return accessor(index, new SetWindowRect())! as SetWindowRect;
    case 'DetachWindow': return accessor(index, new DetachWindow())! as DetachWindow;
    default: return null;
  }
}
