// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SetWindowRect {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetWindowRect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetWindowRect(bb:flatbuffers.ByteBuffer, obj?:SetWindowRect):SetWindowRect {
  return (obj || new SetWindowRect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetWindowRect(bb:flatbuffers.ByteBuffer, obj?:SetWindowRect):SetWindowRect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetWindowRect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startSetWindowRect(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldInt32(0, x, 0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldInt32(1, y, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(2, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(3, height, 0);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(4, id, 0);
}

static endSetWindowRect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetWindowRect(builder:flatbuffers.Builder, x:number, y:number, width:number, height:number, id:number):flatbuffers.Offset {
  SetWindowRect.startSetWindowRect(builder);
  SetWindowRect.addX(builder, x);
  SetWindowRect.addY(builder, y);
  SetWindowRect.addWidth(builder, width);
  SetWindowRect.addHeight(builder, height);
  SetWindowRect.addId(builder, id);
  return SetWindowRect.endSetWindowRect(builder);
}
}
