// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_IPCPROTOCOL_H_
#define FLATBUFFERS_GENERATED_IPCPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "ipc_nativewindow.h"
#include "ipc_streampreview.h"

struct Envelope;
struct EnvelopeBuilder;

enum Domain : int8_t {
  Domain_None = 0,
  Domain_NativeWindow = 1,
  Domain_StreamPreview = 2,
  Domain_MIN = Domain_None,
  Domain_MAX = Domain_StreamPreview
};

inline const Domain (&EnumValuesDomain())[3] {
  static const Domain values[] = {
    Domain_None,
    Domain_NativeWindow,
    Domain_StreamPreview
  };
  return values;
}

inline const char * const *EnumNamesDomain() {
  static const char * const names[4] = {
    "None",
    "NativeWindow",
    "StreamPreview",
    nullptr
  };
  return names;
}

inline const char *EnumNameDomain(Domain e) {
  if (::flatbuffers::IsOutRange(e, Domain_None, Domain_StreamPreview)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDomain()[index];
}

struct Envelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DOMAIN = 4,
    VT_NATIVE_WINDOW_TYPE = 6,
    VT_NATIVE_WINDOW = 8,
    VT_STREAM_PREVIEW_TYPE = 10,
    VT_STREAM_PREVIEW = 12
  };
  Domain domain() const {
    return static_cast<Domain>(GetField<int8_t>(VT_DOMAIN, 0));
  }
  NativeWindowPayload native_window_type() const {
    return static_cast<NativeWindowPayload>(GetField<uint8_t>(VT_NATIVE_WINDOW_TYPE, 0));
  }
  const void *native_window() const {
    return GetPointer<const void *>(VT_NATIVE_WINDOW);
  }
  template<typename T> const T *native_window_as() const;
  const AttachNativeWindow *native_window_as_AttachNativeWindow() const {
    return native_window_type() == NativeWindowPayload_AttachNativeWindow ? static_cast<const AttachNativeWindow *>(native_window()) : nullptr;
  }
  const SetNativeWindowRect *native_window_as_SetNativeWindowRect() const {
    return native_window_type() == NativeWindowPayload_SetNativeWindowRect ? static_cast<const SetNativeWindowRect *>(native_window()) : nullptr;
  }
  const DetachNativeWindow *native_window_as_DetachNativeWindow() const {
    return native_window_type() == NativeWindowPayload_DetachNativeWindow ? static_cast<const DetachNativeWindow *>(native_window()) : nullptr;
  }
  const ReleaseNativeWindow *native_window_as_ReleaseNativeWindow() const {
    return native_window_type() == NativeWindowPayload_ReleaseNativeWindow ? static_cast<const ReleaseNativeWindow *>(native_window()) : nullptr;
  }
  StreamPreviewPayload stream_preview_type() const {
    return static_cast<StreamPreviewPayload>(GetField<uint8_t>(VT_STREAM_PREVIEW_TYPE, 0));
  }
  const void *stream_preview() const {
    return GetPointer<const void *>(VT_STREAM_PREVIEW);
  }
  template<typename T> const T *stream_preview_as() const;
  const PresentVideoFrame *stream_preview_as_PresentVideoFrame() const {
    return stream_preview_type() == StreamPreviewPayload_PresentVideoFrame ? static_cast<const PresentVideoFrame *>(stream_preview()) : nullptr;
  }
  const ReleaseVideoFrame *stream_preview_as_ReleaseVideoFrame() const {
    return stream_preview_type() == StreamPreviewPayload_ReleaseVideoFrame ? static_cast<const ReleaseVideoFrame *>(stream_preview()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_DOMAIN, 1) &&
           VerifyField<uint8_t>(verifier, VT_NATIVE_WINDOW_TYPE, 1) &&
           VerifyOffset(verifier, VT_NATIVE_WINDOW) &&
           VerifyNativeWindowPayload(verifier, native_window(), native_window_type()) &&
           VerifyField<uint8_t>(verifier, VT_STREAM_PREVIEW_TYPE, 1) &&
           VerifyOffset(verifier, VT_STREAM_PREVIEW) &&
           VerifyStreamPreviewPayload(verifier, stream_preview(), stream_preview_type()) &&
           verifier.EndTable();
  }
};

template<> inline const AttachNativeWindow *Envelope::native_window_as<AttachNativeWindow>() const {
  return native_window_as_AttachNativeWindow();
}

template<> inline const SetNativeWindowRect *Envelope::native_window_as<SetNativeWindowRect>() const {
  return native_window_as_SetNativeWindowRect();
}

template<> inline const DetachNativeWindow *Envelope::native_window_as<DetachNativeWindow>() const {
  return native_window_as_DetachNativeWindow();
}

template<> inline const ReleaseNativeWindow *Envelope::native_window_as<ReleaseNativeWindow>() const {
  return native_window_as_ReleaseNativeWindow();
}

template<> inline const PresentVideoFrame *Envelope::stream_preview_as<PresentVideoFrame>() const {
  return stream_preview_as_PresentVideoFrame();
}

template<> inline const ReleaseVideoFrame *Envelope::stream_preview_as<ReleaseVideoFrame>() const {
  return stream_preview_as_ReleaseVideoFrame();
}

struct EnvelopeBuilder {
  typedef Envelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_domain(Domain domain) {
    fbb_.AddElement<int8_t>(Envelope::VT_DOMAIN, static_cast<int8_t>(domain), 0);
  }
  void add_native_window_type(NativeWindowPayload native_window_type) {
    fbb_.AddElement<uint8_t>(Envelope::VT_NATIVE_WINDOW_TYPE, static_cast<uint8_t>(native_window_type), 0);
  }
  void add_native_window(::flatbuffers::Offset<void> native_window) {
    fbb_.AddOffset(Envelope::VT_NATIVE_WINDOW, native_window);
  }
  void add_stream_preview_type(StreamPreviewPayload stream_preview_type) {
    fbb_.AddElement<uint8_t>(Envelope::VT_STREAM_PREVIEW_TYPE, static_cast<uint8_t>(stream_preview_type), 0);
  }
  void add_stream_preview(::flatbuffers::Offset<void> stream_preview) {
    fbb_.AddOffset(Envelope::VT_STREAM_PREVIEW, stream_preview);
  }
  explicit EnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Envelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Envelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Envelope> CreateEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Domain domain = Domain_None,
    NativeWindowPayload native_window_type = NativeWindowPayload_NONE,
    ::flatbuffers::Offset<void> native_window = 0,
    StreamPreviewPayload stream_preview_type = StreamPreviewPayload_NONE,
    ::flatbuffers::Offset<void> stream_preview = 0) {
  EnvelopeBuilder builder_(_fbb);
  builder_.add_stream_preview(stream_preview);
  builder_.add_native_window(native_window);
  builder_.add_stream_preview_type(stream_preview_type);
  builder_.add_native_window_type(native_window_type);
  builder_.add_domain(domain);
  return builder_.Finish();
}

inline const Envelope *GetEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<Envelope>(buf);
}

inline const Envelope *GetSizePrefixedEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Envelope>(buf);
}

inline bool VerifyEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Envelope>(nullptr);
}

inline bool VerifySizePrefixedEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Envelope>(nullptr);
}

inline void FinishEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Envelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Envelope> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_IPCPROTOCOL_H_
