// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_IPCSTREAMPREVIEW_H_
#define FLATBUFFERS_GENERATED_IPCSTREAMPREVIEW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct PresentVideoFrame;
struct PresentVideoFrameBuilder;

struct ReleaseVideoFrame;
struct ReleaseVideoFrameBuilder;

enum StreamPreviewPayload : uint8_t {
  StreamPreviewPayload_NONE = 0,
  StreamPreviewPayload_PresentVideoFrame = 1,
  StreamPreviewPayload_ReleaseVideoFrame = 2,
  StreamPreviewPayload_MIN = StreamPreviewPayload_NONE,
  StreamPreviewPayload_MAX = StreamPreviewPayload_ReleaseVideoFrame
};

inline const StreamPreviewPayload (&EnumValuesStreamPreviewPayload())[3] {
  static const StreamPreviewPayload values[] = {
    StreamPreviewPayload_NONE,
    StreamPreviewPayload_PresentVideoFrame,
    StreamPreviewPayload_ReleaseVideoFrame
  };
  return values;
}

inline const char * const *EnumNamesStreamPreviewPayload() {
  static const char * const names[4] = {
    "NONE",
    "PresentVideoFrame",
    "ReleaseVideoFrame",
    nullptr
  };
  return names;
}

inline const char *EnumNameStreamPreviewPayload(StreamPreviewPayload e) {
  if (::flatbuffers::IsOutRange(e, StreamPreviewPayload_NONE, StreamPreviewPayload_ReleaseVideoFrame)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStreamPreviewPayload()[index];
}

template<typename T> struct StreamPreviewPayloadTraits {
  static const StreamPreviewPayload enum_value = StreamPreviewPayload_NONE;
};

template<> struct StreamPreviewPayloadTraits<PresentVideoFrame> {
  static const StreamPreviewPayload enum_value = StreamPreviewPayload_PresentVideoFrame;
};

template<> struct StreamPreviewPayloadTraits<ReleaseVideoFrame> {
  static const StreamPreviewPayload enum_value = StreamPreviewPayload_ReleaseVideoFrame;
};

bool VerifyStreamPreviewPayload(::flatbuffers::Verifier &verifier, const void *obj, StreamPreviewPayload type);
bool VerifyStreamPreviewPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct PresentVideoFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PresentVideoFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TOKEN = 6,
    VT_HANDLE = 8,
    VT_WIDTH = 10,
    VT_HEIGHT = 12,
    VT_TIMESTAMP_US = 14
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  uint64_t handle() const {
    return GetField<uint64_t>(VT_HANDLE, 0);
  }
  uint32_t width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  int64_t timestamp_us() const {
    return GetField<int64_t>(VT_TIMESTAMP_US, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN, 8) &&
           VerifyField<uint64_t>(verifier, VT_HANDLE, 8) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP_US, 8) &&
           verifier.EndTable();
  }
};

struct PresentVideoFrameBuilder {
  typedef PresentVideoFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(PresentVideoFrame::VT_ID, id, 0);
  }
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(PresentVideoFrame::VT_TOKEN, token, 0);
  }
  void add_handle(uint64_t handle) {
    fbb_.AddElement<uint64_t>(PresentVideoFrame::VT_HANDLE, handle, 0);
  }
  void add_width(uint32_t width) {
    fbb_.AddElement<uint32_t>(PresentVideoFrame::VT_WIDTH, width, 0);
  }
  void add_height(uint32_t height) {
    fbb_.AddElement<uint32_t>(PresentVideoFrame::VT_HEIGHT, height, 0);
  }
  void add_timestamp_us(int64_t timestamp_us) {
    fbb_.AddElement<int64_t>(PresentVideoFrame::VT_TIMESTAMP_US, timestamp_us, 0);
  }
  explicit PresentVideoFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PresentVideoFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PresentVideoFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PresentVideoFrame> CreatePresentVideoFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint64_t token = 0,
    uint64_t handle = 0,
    uint32_t width = 0,
    uint32_t height = 0,
    int64_t timestamp_us = 0) {
  PresentVideoFrameBuilder builder_(_fbb);
  builder_.add_timestamp_us(timestamp_us);
  builder_.add_handle(handle);
  builder_.add_token(token);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_id(id);
  return builder_.Finish();
}

struct ReleaseVideoFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReleaseVideoFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TOKEN = 6
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN, 8) &&
           verifier.EndTable();
  }
};

struct ReleaseVideoFrameBuilder {
  typedef ReleaseVideoFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ReleaseVideoFrame::VT_ID, id, 0);
  }
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(ReleaseVideoFrame::VT_TOKEN, token, 0);
  }
  explicit ReleaseVideoFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReleaseVideoFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReleaseVideoFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReleaseVideoFrame> CreateReleaseVideoFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint64_t token = 0) {
  ReleaseVideoFrameBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_id(id);
  return builder_.Finish();
}

inline bool VerifyStreamPreviewPayload(::flatbuffers::Verifier &verifier, const void *obj, StreamPreviewPayload type) {
  switch (type) {
    case StreamPreviewPayload_NONE: {
      return true;
    }
    case StreamPreviewPayload_PresentVideoFrame: {
      auto ptr = reinterpret_cast<const PresentVideoFrame *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case StreamPreviewPayload_ReleaseVideoFrame: {
      auto ptr = reinterpret_cast<const ReleaseVideoFrame *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyStreamPreviewPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyStreamPreviewPayload(
        verifier,  values->Get(i), types->GetEnum<StreamPreviewPayload>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_IPCSTREAMPREVIEW_H_
