// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_IPCNATIVEWINDOW_H_
#define FLATBUFFERS_GENERATED_IPCNATIVEWINDOW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct AttachNativeWindow;
struct AttachNativeWindowBuilder;

struct SetNativeWindowRect;
struct SetNativeWindowRectBuilder;

struct DetachNativeWindow;
struct DetachNativeWindowBuilder;

struct ReleaseNativeWindow;
struct ReleaseNativeWindowBuilder;

enum NativeWindowPayload : uint8_t {
  NativeWindowPayload_NONE = 0,
  NativeWindowPayload_AttachNativeWindow = 1,
  NativeWindowPayload_SetNativeWindowRect = 2,
  NativeWindowPayload_DetachNativeWindow = 3,
  NativeWindowPayload_ReleaseNativeWindow = 4,
  NativeWindowPayload_MIN = NativeWindowPayload_NONE,
  NativeWindowPayload_MAX = NativeWindowPayload_ReleaseNativeWindow
};

inline const NativeWindowPayload (&EnumValuesNativeWindowPayload())[5] {
  static const NativeWindowPayload values[] = {
    NativeWindowPayload_NONE,
    NativeWindowPayload_AttachNativeWindow,
    NativeWindowPayload_SetNativeWindowRect,
    NativeWindowPayload_DetachNativeWindow,
    NativeWindowPayload_ReleaseNativeWindow
  };
  return values;
}

inline const char * const *EnumNamesNativeWindowPayload() {
  static const char * const names[6] = {
    "NONE",
    "AttachNativeWindow",
    "SetNativeWindowRect",
    "DetachNativeWindow",
    "ReleaseNativeWindow",
    nullptr
  };
  return names;
}

inline const char *EnumNameNativeWindowPayload(NativeWindowPayload e) {
  if (::flatbuffers::IsOutRange(e, NativeWindowPayload_NONE, NativeWindowPayload_ReleaseNativeWindow)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNativeWindowPayload()[index];
}

template<typename T> struct NativeWindowPayloadTraits {
  static const NativeWindowPayload enum_value = NativeWindowPayload_NONE;
};

template<> struct NativeWindowPayloadTraits<AttachNativeWindow> {
  static const NativeWindowPayload enum_value = NativeWindowPayload_AttachNativeWindow;
};

template<> struct NativeWindowPayloadTraits<SetNativeWindowRect> {
  static const NativeWindowPayload enum_value = NativeWindowPayload_SetNativeWindowRect;
};

template<> struct NativeWindowPayloadTraits<DetachNativeWindow> {
  static const NativeWindowPayload enum_value = NativeWindowPayload_DetachNativeWindow;
};

template<> struct NativeWindowPayloadTraits<ReleaseNativeWindow> {
  static const NativeWindowPayload enum_value = NativeWindowPayload_ReleaseNativeWindow;
};

bool VerifyNativeWindowPayload(::flatbuffers::Verifier &verifier, const void *obj, NativeWindowPayload type);
bool VerifyNativeWindowPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct AttachNativeWindow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AttachNativeWindowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARENT_HANDLE = 4,
    VT_SHOW = 6,
    VT_ID = 8
  };
  uint64_t parent_handle() const {
    return GetField<uint64_t>(VT_PARENT_HANDLE, 0);
  }
  bool show() const {
    return GetField<uint8_t>(VT_SHOW, 0) != 0;
  }
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PARENT_HANDLE, 8) &&
           VerifyField<uint8_t>(verifier, VT_SHOW, 1) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct AttachNativeWindowBuilder {
  typedef AttachNativeWindow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parent_handle(uint64_t parent_handle) {
    fbb_.AddElement<uint64_t>(AttachNativeWindow::VT_PARENT_HANDLE, parent_handle, 0);
  }
  void add_show(bool show) {
    fbb_.AddElement<uint8_t>(AttachNativeWindow::VT_SHOW, static_cast<uint8_t>(show), 0);
  }
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(AttachNativeWindow::VT_ID, id, 0);
  }
  explicit AttachNativeWindowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AttachNativeWindow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AttachNativeWindow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AttachNativeWindow> CreateAttachNativeWindow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t parent_handle = 0,
    bool show = false,
    uint32_t id = 0) {
  AttachNativeWindowBuilder builder_(_fbb);
  builder_.add_parent_handle(parent_handle);
  builder_.add_id(id);
  builder_.add_show(show);
  return builder_.Finish();
}

struct SetNativeWindowRect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetNativeWindowRectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10,
    VT_ID = 12
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  int32_t width() const {
    return GetField<int32_t>(VT_WIDTH, 0);
  }
  int32_t height() const {
    return GetField<int32_t>(VT_HEIGHT, 0);
  }
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<int32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct SetNativeWindowRectBuilder {
  typedef SetNativeWindowRect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(SetNativeWindowRect::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(SetNativeWindowRect::VT_Y, y, 0);
  }
  void add_width(int32_t width) {
    fbb_.AddElement<int32_t>(SetNativeWindowRect::VT_WIDTH, width, 0);
  }
  void add_height(int32_t height) {
    fbb_.AddElement<int32_t>(SetNativeWindowRect::VT_HEIGHT, height, 0);
  }
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(SetNativeWindowRect::VT_ID, id, 0);
  }
  explicit SetNativeWindowRectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetNativeWindowRect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetNativeWindowRect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetNativeWindowRect> CreateSetNativeWindowRect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0,
    int32_t width = 0,
    int32_t height = 0,
    uint32_t id = 0) {
  SetNativeWindowRectBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct DetachNativeWindow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DetachNativeWindowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct DetachNativeWindowBuilder {
  typedef DetachNativeWindow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(DetachNativeWindow::VT_ID, id, 0);
  }
  explicit DetachNativeWindowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DetachNativeWindow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DetachNativeWindow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DetachNativeWindow> CreateDetachNativeWindow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  DetachNativeWindowBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct ReleaseNativeWindow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReleaseNativeWindowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct ReleaseNativeWindowBuilder {
  typedef ReleaseNativeWindow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ReleaseNativeWindow::VT_ID, id, 0);
  }
  explicit ReleaseNativeWindowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReleaseNativeWindow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReleaseNativeWindow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReleaseNativeWindow> CreateReleaseNativeWindow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  ReleaseNativeWindowBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

inline bool VerifyNativeWindowPayload(::flatbuffers::Verifier &verifier, const void *obj, NativeWindowPayload type) {
  switch (type) {
    case NativeWindowPayload_NONE: {
      return true;
    }
    case NativeWindowPayload_AttachNativeWindow: {
      auto ptr = reinterpret_cast<const AttachNativeWindow *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NativeWindowPayload_SetNativeWindowRect: {
      auto ptr = reinterpret_cast<const SetNativeWindowRect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NativeWindowPayload_DetachNativeWindow: {
      auto ptr = reinterpret_cast<const DetachNativeWindow *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NativeWindowPayload_ReleaseNativeWindow: {
      auto ptr = reinterpret_cast<const ReleaseNativeWindow *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyNativeWindowPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyNativeWindowPayload(
        verifier,  values->Get(i), types->GetEnum<NativeWindowPayload>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_IPCNATIVEWINDOW_H_
