// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AttachNativeWindow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AttachNativeWindow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttachNativeWindow(bb:flatbuffers.ByteBuffer, obj?:AttachNativeWindow):AttachNativeWindow {
  return (obj || new AttachNativeWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttachNativeWindow(bb:flatbuffers.ByteBuffer, obj?:AttachNativeWindow):AttachNativeWindow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AttachNativeWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

parentHandle():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

show():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startAttachNativeWindow(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addParentHandle(builder:flatbuffers.Builder, parentHandle:bigint) {
  builder.addFieldInt64(0, parentHandle, BigInt('0'));
}

static addShow(builder:flatbuffers.Builder, show:boolean) {
  builder.addFieldInt8(1, +show, +false);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(2, id, 0);
}

static endAttachNativeWindow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttachNativeWindow(builder:flatbuffers.Builder, parentHandle:bigint, show:boolean, id:number):flatbuffers.Offset {
  AttachNativeWindow.startAttachNativeWindow(builder);
  AttachNativeWindow.addParentHandle(builder, parentHandle);
  AttachNativeWindow.addShow(builder, show);
  AttachNativeWindow.addId(builder, id);
  return AttachNativeWindow.endAttachNativeWindow(builder);
}
}
