// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Domain } from './domain.js';
import { NativeWindowPayload, unionToNativeWindowPayload, unionListToNativeWindowPayload } from './native-window-payload.js';
import { StreamPreviewPayload, unionToStreamPreviewPayload, unionListToStreamPreviewPayload } from './stream-preview-payload.js';


export class Envelope {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Envelope {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEnvelope(bb:flatbuffers.ByteBuffer, obj?:Envelope):Envelope {
  return (obj || new Envelope()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEnvelope(bb:flatbuffers.ByteBuffer, obj?:Envelope):Envelope {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Envelope()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

domain():Domain {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : Domain.None;
}

nativeWindowType():NativeWindowPayload {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : NativeWindowPayload.NONE;
}

nativeWindow<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

streamPreviewType():StreamPreviewPayload {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StreamPreviewPayload.NONE;
}

streamPreview<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startEnvelope(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addDomain(builder:flatbuffers.Builder, domain:Domain) {
  builder.addFieldInt8(0, domain, Domain.None);
}

static addNativeWindowType(builder:flatbuffers.Builder, nativeWindowType:NativeWindowPayload) {
  builder.addFieldInt8(1, nativeWindowType, NativeWindowPayload.NONE);
}

static addNativeWindow(builder:flatbuffers.Builder, nativeWindowOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nativeWindowOffset, 0);
}

static addStreamPreviewType(builder:flatbuffers.Builder, streamPreviewType:StreamPreviewPayload) {
  builder.addFieldInt8(3, streamPreviewType, StreamPreviewPayload.NONE);
}

static addStreamPreview(builder:flatbuffers.Builder, streamPreviewOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, streamPreviewOffset, 0);
}

static endEnvelope(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishEnvelopeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedEnvelopeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createEnvelope(builder:flatbuffers.Builder, domain:Domain, nativeWindowType:NativeWindowPayload, nativeWindowOffset:flatbuffers.Offset, streamPreviewType:StreamPreviewPayload, streamPreviewOffset:flatbuffers.Offset):flatbuffers.Offset {
  Envelope.startEnvelope(builder);
  Envelope.addDomain(builder, domain);
  Envelope.addNativeWindowType(builder, nativeWindowType);
  Envelope.addNativeWindow(builder, nativeWindowOffset);
  Envelope.addStreamPreviewType(builder, streamPreviewType);
  Envelope.addStreamPreview(builder, streamPreviewOffset);
  return Envelope.endEnvelope(builder);
}
}
