// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AttachNativeWindow } from './attach-native-window.js';
import { DetachNativeWindow } from './detach-native-window.js';
import { ReleaseNativeWindow } from './release-native-window.js';
import { SetNativeWindowRect } from './set-native-window-rect.js';


export enum NativeWindowPayload {
  NONE = 0,
  AttachNativeWindow = 1,
  SetNativeWindowRect = 2,
  DetachNativeWindow = 3,
  ReleaseNativeWindow = 4
}

export function unionToNativeWindowPayload(
  type: NativeWindowPayload,
  accessor: (obj:AttachNativeWindow|DetachNativeWindow|ReleaseNativeWindow|SetNativeWindowRect) => AttachNativeWindow|DetachNativeWindow|ReleaseNativeWindow|SetNativeWindowRect|null
): AttachNativeWindow|DetachNativeWindow|ReleaseNativeWindow|SetNativeWindowRect|null {
  switch(NativeWindowPayload[type]) {
    case 'NONE': return null; 
    case 'AttachNativeWindow': return accessor(new AttachNativeWindow())! as AttachNativeWindow;
    case 'SetNativeWindowRect': return accessor(new SetNativeWindowRect())! as SetNativeWindowRect;
    case 'DetachNativeWindow': return accessor(new DetachNativeWindow())! as DetachNativeWindow;
    case 'ReleaseNativeWindow': return accessor(new ReleaseNativeWindow())! as ReleaseNativeWindow;
    default: return null;
  }
}

export function unionListToNativeWindowPayload(
  type: NativeWindowPayload, 
  accessor: (index: number, obj:AttachNativeWindow|DetachNativeWindow|ReleaseNativeWindow|SetNativeWindowRect) => AttachNativeWindow|DetachNativeWindow|ReleaseNativeWindow|SetNativeWindowRect|null, 
  index: number
): AttachNativeWindow|DetachNativeWindow|ReleaseNativeWindow|SetNativeWindowRect|null {
  switch(NativeWindowPayload[type]) {
    case 'NONE': return null; 
    case 'AttachNativeWindow': return accessor(index, new AttachNativeWindow())! as AttachNativeWindow;
    case 'SetNativeWindowRect': return accessor(index, new SetNativeWindowRect())! as SetNativeWindowRect;
    case 'DetachNativeWindow': return accessor(index, new DetachNativeWindow())! as DetachNativeWindow;
    case 'ReleaseNativeWindow': return accessor(index, new ReleaseNativeWindow())! as ReleaseNativeWindow;
    default: return null;
  }
}
