// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PresentVideoFrame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PresentVideoFrame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPresentVideoFrame(bb:flatbuffers.ByteBuffer, obj?:PresentVideoFrame):PresentVideoFrame {
  return (obj || new PresentVideoFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPresentVideoFrame(bb:flatbuffers.ByteBuffer, obj?:PresentVideoFrame):PresentVideoFrame {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PresentVideoFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

token():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

handle():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

timestampUs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startPresentVideoFrame(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addToken(builder:flatbuffers.Builder, token:bigint) {
  builder.addFieldInt64(1, token, BigInt('0'));
}

static addHandle(builder:flatbuffers.Builder, handle:bigint) {
  builder.addFieldInt64(2, handle, BigInt('0'));
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(3, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(4, height, 0);
}

static addTimestampUs(builder:flatbuffers.Builder, timestampUs:bigint) {
  builder.addFieldInt64(5, timestampUs, BigInt('0'));
}

static endPresentVideoFrame(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPresentVideoFrame(builder:flatbuffers.Builder, id:number, token:bigint, handle:bigint, width:number, height:number, timestampUs:bigint):flatbuffers.Offset {
  PresentVideoFrame.startPresentVideoFrame(builder);
  PresentVideoFrame.addId(builder, id);
  PresentVideoFrame.addToken(builder, token);
  PresentVideoFrame.addHandle(builder, handle);
  PresentVideoFrame.addWidth(builder, width);
  PresentVideoFrame.addHeight(builder, height);
  PresentVideoFrame.addTimestampUs(builder, timestampUs);
  return PresentVideoFrame.endPresentVideoFrame(builder);
}
}
