// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ReleaseNativeWindow {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReleaseNativeWindow {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReleaseNativeWindow(bb:flatbuffers.ByteBuffer, obj?:ReleaseNativeWindow):ReleaseNativeWindow {
  return (obj || new ReleaseNativeWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReleaseNativeWindow(bb:flatbuffers.ByteBuffer, obj?:ReleaseNativeWindow):ReleaseNativeWindow {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReleaseNativeWindow()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startReleaseNativeWindow(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endReleaseNativeWindow(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReleaseNativeWindow(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  ReleaseNativeWindow.startReleaseNativeWindow(builder);
  ReleaseNativeWindow.addId(builder, id);
  return ReleaseNativeWindow.endReleaseNativeWindow(builder);
}
}
