// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ReleaseStreamPreview {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReleaseStreamPreview {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReleaseStreamPreview(bb:flatbuffers.ByteBuffer, obj?:ReleaseStreamPreview):ReleaseStreamPreview {
  return (obj || new ReleaseStreamPreview()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReleaseStreamPreview(bb:flatbuffers.ByteBuffer, obj?:ReleaseStreamPreview):ReleaseStreamPreview {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReleaseStreamPreview()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startReleaseStreamPreview(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endReleaseStreamPreview(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReleaseStreamPreview(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  ReleaseStreamPreview.startReleaseStreamPreview(builder);
  ReleaseStreamPreview.addId(builder, id);
  return ReleaseStreamPreview.endReleaseStreamPreview(builder);
}
}
