// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ReleaseVideoFrame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReleaseVideoFrame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReleaseVideoFrame(bb:flatbuffers.ByteBuffer, obj?:ReleaseVideoFrame):ReleaseVideoFrame {
  return (obj || new ReleaseVideoFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReleaseVideoFrame(bb:flatbuffers.ByteBuffer, obj?:ReleaseVideoFrame):ReleaseVideoFrame {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReleaseVideoFrame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

token():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startReleaseVideoFrame(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addToken(builder:flatbuffers.Builder, token:bigint) {
  builder.addFieldInt64(1, token, BigInt('0'));
}

static endReleaseVideoFrame(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReleaseVideoFrame(builder:flatbuffers.Builder, id:number, token:bigint):flatbuffers.Offset {
  ReleaseVideoFrame.startReleaseVideoFrame(builder);
  ReleaseVideoFrame.addId(builder, id);
  ReleaseVideoFrame.addToken(builder, token);
  return ReleaseVideoFrame.endReleaseVideoFrame(builder);
}
}
