// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { PresentVideoFrame } from './present-video-frame.js';
import { ReleaseVideoFrame } from './release-video-frame.js';


export enum StreamPreviewPayload {
  NONE = 0,
  PresentVideoFrame = 1,
  ReleaseVideoFrame = 2
}

export function unionToStreamPreviewPayload(
  type: StreamPreviewPayload,
  accessor: (obj:PresentVideoFrame|ReleaseVideoFrame) => PresentVideoFrame|ReleaseVideoFrame|null
): PresentVideoFrame|ReleaseVideoFrame|null {
  switch(StreamPreviewPayload[type]) {
    case 'NONE': return null; 
    case 'PresentVideoFrame': return accessor(new PresentVideoFrame())! as PresentVideoFrame;
    case 'ReleaseVideoFrame': return accessor(new ReleaseVideoFrame())! as ReleaseVideoFrame;
    default: return null;
  }
}

export function unionListToStreamPreviewPayload(
  type: StreamPreviewPayload, 
  accessor: (index: number, obj:PresentVideoFrame|ReleaseVideoFrame) => PresentVideoFrame|ReleaseVideoFrame|null, 
  index: number
): PresentVideoFrame|ReleaseVideoFrame|null {
  switch(StreamPreviewPayload[type]) {
    case 'NONE': return null; 
    case 'PresentVideoFrame': return accessor(index, new PresentVideoFrame())! as PresentVideoFrame;
    case 'ReleaseVideoFrame': return accessor(index, new ReleaseVideoFrame())! as ReleaseVideoFrame;
    default: return null;
  }
}
