#!/usr/bin/env python3
"""用 flatc 把 schema/*.fbs 生成 C++ 与 TypeScript 协议代码。

用法：
    python scripts/schema.py              # 缺 flatc / flatbuffers 头文件时自动下载
    python scripts/schema.py --no-fetch   # 只用 PATH / core/thirdparty 里已有的 flatc
    python scripts/schema.py --flatc=...  # 指定 flatc 可执行文件
    python scripts/schema.py --clean      # 生成前删掉这些 schema 的旧产物

win/sh 包装（仓库根目录，双击可用）：schema-win-x84_64.bat / schema-linux-x86_64.sh

输出：
    core/common/            <schema>_generated.h   （C++，供 media-service 用）
    electron/src/common/    <schema>.ts            （TS，import 'flatbuffers' 运行时）

flatc 版本与 electron/package.json 里的 flatbuffers 依赖保持一致（25.9.23），
两者版本必须相同，否则生成的 TS 可能与运行时对不上。
生成的 C++ 要 #include "flatbuffers/flatbuffers.h"：头文件也由本脚本铺到
core/thirdparty/flatbuffers（版本与 flatc 相同，flatc 产出的代码里有 static_assert）。
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
import tarfile
import time
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "schema"
CPP_OUT_DIR = ROOT / "core" / "common"
TS_OUT_DIR = ROOT / "electron" / "src" / "common"
FLATC_DIR = ROOT / "core" / "thirdparty" / "flatc"
TEMP_DIR = ROOT / "build" / "tmp"

# 换版本时改这三个常量，并同步 electron/package.json 的 flatbuffers 版本
FLATC_VERSION = "25.9.23"
FLATC_ARCHIVE = "Windows.flatc.binary-{0}.zip".format(FLATC_VERSION)
FLATC_URL = (
    "https://github.com/google/flatbuffers/releases/download/"
    "v{0}/Windows.flatc.binary.zip".format(FLATC_VERSION)
)
FLATC_SHA256 = "3d6383193ecd274f5de544a6e03464a87f581befb9fc1dda9cf508fa3cce3127"

# flatbuffers 的 C++ 头文件：版本必须和 flatc 相同，否则生成的代码编译不过（static_assert）
FLATBUFFERS_DIR = ROOT / "core" / "thirdparty" / "flatbuffers"
FLATBUFFERS_INCLUDE_DIR = FLATBUFFERS_DIR / "include"
FLATBUFFERS_ARCHIVE = "flatbuffers-{0}-src.tar.gz".format(FLATC_VERSION)
FLATBUFFERS_URL = (
    "https://github.com/google/flatbuffers/archive/refs/tags/"
    "v{0}.tar.gz".format(FLATC_VERSION)
)
FLATBUFFERS_SHA256 = "9102253214dea6ae10c2ac966ea1ed2155d22202390b532d1dea64935c518ada"

GENERATED_MARKER = "// automatically generated by the FlatBuffers compiler"


def configure_streams() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            if stream.isatty():
                stream.reconfigure(errors="replace")
            else:
                stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


configure_streams()


def log(message: str) -> None:
    print("[schema] " + message, flush=True)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fetch_archive(url: str, archive: Path, sha256: str) -> Path:
    """下载并校验压缩包；缓存命中（sha256 一致）就直接用，不再联网。"""
    if archive.exists() and file_sha256(archive) != sha256:
        log("压缩包校验不符，重新下载: " + archive.name)
        archive.unlink()
    if not archive.exists():
        archive.parent.mkdir(parents=True, exist_ok=True)
        log("下载 " + url)
        urllib.request.urlretrieve(url, archive)
    digest = file_sha256(archive)
    if digest != sha256:
        raise SystemExit(
            "[schema] sha256 不符：期望 {0}，实际 {1}".format(sha256, digest)
        )
    return archive


def download_flatc() -> Path:
    exe = FLATC_DIR / "flatc.exe"
    if sys.platform != "win32":
        raise SystemExit("[schema] 只有 Windows 预编译包，请自行安装 flatc 后用 --flatc= 指定")
    archive = fetch_archive(FLATC_URL, TEMP_DIR / FLATC_ARCHIVE, FLATC_SHA256)
    FLATC_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive) as package:
        package.extractall(FLATC_DIR)
    log("flatc 已铺到 " + str(exe))
    return exe


def flatbuffers_headers_ready() -> bool:
    base = FLATBUFFERS_INCLUDE_DIR / "flatbuffers" / "base.h"
    if not base.exists():
        return False
    text = base.read_text(encoding="utf-8", errors="replace")
    for key, value in zip(("MAJOR", "MINOR", "REVISION"), FLATC_VERSION.split(".")):
        if "#define FLATBUFFERS_VERSION_{0} {1}".format(key, value) not in text:
            return False
    return True


def ensure_flatbuffers_headers() -> None:
    """把 flatbuffers 的 C++ 头文件铺到 core/thirdparty（生成的 C++ 要 include 它们）。"""
    if flatbuffers_headers_ready():
        return
    if FLATBUFFERS_INCLUDE_DIR.exists():
        shutil.rmtree(FLATBUFFERS_INCLUDE_DIR)
    archive = fetch_archive(
        FLATBUFFERS_URL, TEMP_DIR / FLATBUFFERS_ARCHIVE, FLATBUFFERS_SHA256
    )
    prefix = "flatbuffers-{0}/include/flatbuffers/".format(FLATC_VERSION)
    count = 0
    with tarfile.open(archive) as package:
        for member in package.getmembers():
            if not member.isfile() or not member.name.startswith(prefix):
                continue
            source = package.extractfile(member)
            if source is None:
                continue
            target = FLATBUFFERS_INCLUDE_DIR / "flatbuffers" / member.name[len(prefix):]
            target.parent.mkdir(parents=True, exist_ok=True)
            with target.open("wb") as handle:
                shutil.copyfileobj(source, handle)
            count += 1
    log("flatbuffers 头文件 -> {0}（{1} 个文件）".format(FLATBUFFERS_INCLUDE_DIR, count))


def find_flatc(explicit: str) -> Path | None:
    if explicit != "":
        path = Path(explicit).resolve()
        if not path.exists():
            raise SystemExit("[schema] --flatc 指定的文件不存在: {0}".format(path))
        return path
    local = FLATC_DIR / "flatc.exe"
    if local.exists():
        return local
    found = shutil.which("flatc")
    return Path(found) if found is not None else None


def collect_schemas() -> list:
    schemas = sorted(SCHEMA_DIR.glob("*.fbs"))
    if not schemas:
        raise SystemExit("[schema] {0} 里没有 .fbs 文件".format(SCHEMA_DIR))
    return schemas


def clean_outputs() -> None:
    # 只删带 flatc 生成标记的文件，手写的 C++/TS 不动
    for folder in (CPP_OUT_DIR, TS_OUT_DIR):
        if not folder.exists():
            continue
        for stale in sorted(folder.iterdir()):
            if not stale.is_file():
                continue
            # utf-8-sig：文件被编辑器存成带 BOM 也要能认出生成标记
            with stale.open("r", encoding="utf-8-sig", errors="replace") as handle:
                generated = handle.readline().startswith(GENERATED_MARKER)
            if generated:
                unlink_with_retry(stale)


def unlink_with_retry(path: Path) -> None:
    # 刚生成的文件可能被杀软/编辑器短暂占用，重试几次再报错
    last_error = None
    for _ in range(5):
        try:
            path.unlink()
            log("删除旧产物 " + str(path))
            return
        except OSError as error:
            last_error = error
            time.sleep(0.4)
    raise SystemExit(
        "[schema] 删不掉旧产物（可能被编辑器占用）: {0} ({1})".format(path, last_error)
    )


def run_flatc(flatc: Path, args: list) -> None:
    command = [str(flatc)] + args
    log(" ".join(command))
    result = subprocess.run(command)
    if result.returncode != 0:
        raise SystemExit("[schema] flatc 失败，退出码 {0}".format(result.returncode))


def generate(flatc: Path, schemas: list) -> None:
    names = [str(path) for path in schemas]
    CPP_OUT_DIR.mkdir(parents=True, exist_ok=True)
    TS_OUT_DIR.mkdir(parents=True, exist_ok=True)
    run_flatc(flatc, ["--cpp", "-o", str(CPP_OUT_DIR)] + names)
    run_flatc(flatc, ["--ts", "-o", str(TS_OUT_DIR)] + names)
    log("C++  -> " + str(CPP_OUT_DIR))
    log("TS   -> " + str(TS_OUT_DIR))


def main() -> int:
    parser = argparse.ArgumentParser(description="用 flatc 生成 C++ 与 TypeScript 协议代码")
    parser.add_argument("--flatc", default="", help="flatc 可执行文件路径")
    parser.add_argument("--no-fetch", action="store_true", help="找不到 flatc 时不自动下载")
    parser.add_argument("--clean", action="store_true", help="生成前删掉旧产物")
    args = parser.parse_args()

    schemas = collect_schemas()
    flatc = find_flatc(args.flatc)
    if flatc is None:
        if args.no_fetch:
            raise SystemExit("[schema] 找不到 flatc：装一个，或用 --flatc= 指定路径")
        flatc = download_flatc()
    log("使用 " + str(flatc))

    if args.no_fetch:
        if not flatbuffers_headers_ready():
            log("--no-fetch：缺 flatbuffers C++ 头文件，编译 C++ 前先跑一次不带 --no-fetch 的生成")
    else:
        ensure_flatbuffers_headers()

    if args.clean:
        clean_outputs()
    generate(flatc, schemas)
    return 0


if __name__ == "__main__":
    sys.exit(main())
