#!/usr/bin/env python3
"""通过 core/cmake 的 generate-schemas target 生成 C++ 与 TypeScript 协议代码。

用法：
    python scripts/schema.py
    python scripts/schema.py --no-fetch
    python scripts/schema.py --flatc=...
    python scripts/schema.py --clean

FlatBuffers 版本、下载地址和校验值统一定义在 core/cmake/FlatBuffers.cmake。
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = ROOT / "core"
BUILD_DIR = ROOT / "build" / "schema"
CPP_OUT_DIR = CORE_DIR / "common"
TS_OUT_DIR = ROOT / "electron" / "src" / "common"
GENERATED_MARKER = "// automatically generated by the FlatBuffers compiler"


def configure_streams() -> None:
    for stream in (sys.stdout, sys.stderr):
        try:
            if stream.isatty():
                stream.reconfigure(errors="replace")
            else:
                stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


configure_streams()


def log(message: str) -> None:
    print("[schema] " + message, flush=True)


def run(command: list[str]) -> None:
    log(" ".join(str(part) for part in command))
    result = subprocess.run([str(part) for part in command])
    if result.returncode != 0:
        raise SystemExit("[schema] 上一条命令失败，退出码 {0}".format(result.returncode))


def find_cmake() -> str:
    cmake = shutil.which("cmake")
    if cmake is None:
        raise SystemExit("[schema] PATH 里找不到 cmake")
    return cmake


def resolve_flatc(explicit: str, no_fetch: bool) -> Path | None:
    if explicit:
        flatc = Path(explicit).resolve()
        if not flatc.is_file():
            raise SystemExit("[schema] --flatc 指定的文件不存在: {0}".format(flatc))
        return flatc
    if not no_fetch:
        return None

    executable = "flatc.exe" if os.name == "nt" else "flatc"
    candidates = [
        BUILD_DIR / "_deps" / "livestreamer_flatc-src" / executable,
        CORE_DIR / "thirdparty" / "flatc" / executable,
    ]
    found = shutil.which("flatc")
    if found:
        candidates.append(Path(found))
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    raise SystemExit("[schema] --no-fetch：找不到已有 flatc，请安装或用 --flatc= 指定")


def unlink_with_retry(path: Path) -> None:
    last_error = None
    for _ in range(5):
        try:
            path.unlink()
            log("删除旧产物 " + str(path))
            return
        except OSError as error:
            last_error = error
            time.sleep(0.4)
    raise SystemExit(
        "[schema] 删不掉旧产物（可能被编辑器占用）: {0} ({1})".format(path, last_error)
    )


def clean_outputs() -> None:
    for folder in (CPP_OUT_DIR, TS_OUT_DIR):
        if not folder.exists():
            continue
        for stale in sorted(folder.iterdir()):
            if not stale.is_file():
                continue
            with stale.open("r", encoding="utf-8-sig", errors="replace") as handle:
                generated = handle.readline().startswith(GENERATED_MARKER)
            if generated:
                unlink_with_retry(stale)


def main() -> int:
    parser = argparse.ArgumentParser(description="用 CMake 管理的 flatc 生成协议代码")
    parser.add_argument("--flatc", default="", help="使用指定的 flatc 可执行文件")
    parser.add_argument("--no-fetch", action="store_true", help="只使用已有的 flatc")
    parser.add_argument("--clean", action="store_true", help="生成前删除旧产物")
    args = parser.parse_args()

    cmake = find_cmake()
    flatc = resolve_flatc(args.flatc, args.no_fetch)
    if args.clean:
        clean_outputs()

    configure = [
        cmake,
        "-S",
        CORE_DIR,
        "-B",
        BUILD_DIR,
        "-DLIVESTREAMER_SCHEMA_ONLY=ON",
        "-DLIVESTREAMER_FLATC:FILEPATH={0}".format(flatc or ""),
    ]
    run(configure)
    run([cmake, "--build", BUILD_DIR, "--target", "generate-schemas"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
